version: '3.9'

services:
  db:
    image: mysql:8
    restart: always
    container_name: db
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: flexidb
    networks:
      test_vm:
        name: test_vm
        driver: bridge
  server:
    container_name: server
    build:
    context: '.'
    target: base
    ports:
      - '4000:4000'
    depends_on:
      - db
    networks:
      - test_vm