version: '3'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=flexidb
      - MYSQL_ROOT_PASSWORD=garancia
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - "db"